'use strict';
// Sprite data for the starter lines, the Demon King and the second wave of monsters: 16×16, one char per pixel, '.' is transparent.

const FORMS = {
  pyrobit: {
    name: 'Pyrobit',
    pal: { o: '#2a0f0a', b: '#ff7a2f', h: '#ffb35c', c: '#ffe0a3', e: '#1a1a1a', w: '#ffffff', m: '#7a1f0f', k: '#fff1d0', f: '#ffd23f', r: '#ff3b1f' },
    rows: [
      '................',
      '................',
      '........ok.ok...',
      '.......obbobbo..',
      '......obhbbbbbo.',
      '......obbbwebbo.',
      '......obbbeebbbo',
      '.......obbbbmmo.',
      '...f...oobbbbo..',
      '..frf.obccbbbbo.',
      '..frrobcccbbbbo.',
      '...rroobccbbbo..',
      '....ooobbbbbbo..',
      '.......obo.obo..',
      '.......oo..oo...',
      '................',
    ],
  },
  blazewyrm: {
    name: 'Blazewyrm',
    pal: { o: '#240a06', b: '#ff6a1f', h: '#ffa84a', c: '#ffd98a', e: '#1a1a1a', w: '#ffffff', m: '#6b1408', k: '#fff1d0', g: '#b8340c', f: '#ffd23f', r: '#ff3b1f' },
    rows: [
      '.o.......ok.ok..',
      '.oo.....obbobbo.',
      '.ogo...obhbbbbbo',
      '.oggo..obbbwebbo',
      '.ogggo.obbbeebbo',
      '.oggggoobbbbbmmo',
      '..ogggobbbbbooo.',
      '...oggobccbbbo..',
      '....oobcccbbbbo.',
      '.f...obcccbbbbo.',
      'frf..obccbbbbbo.',
      'frr.oobbbbbbbo..',
      '.rroobbbbbbbbo..',
      '...ooobbo.obbo..',
      '......okko.okko.',
      '......oooo.oooo.',
    ],
  },
  infernus: {
    name: 'Infernus',
    pal: { o: '#1f0704', b: '#e8461a', h: '#ff9a3c', c: '#ffd27a', e: '#fff36b', w: '#ffffff', m: '#4a0a04', k: '#fff1d0', g: '#9c2408', f: '#ffd23f', r: '#ff3b1f' },
    rows: [
      '..k..........k..',
      '..ko..oooo..ok..',
      'o..koobbbbook..o',
      'oo..obhbbhbo..oo',
      'ogo.oewbbweo.ogo',
      'oggoobbbbbbooggo',
      'ogggobkmmkbogggo',
      'oggggoobbooggggo',
      '.ogggobccbogggo.',
      '..oggobccboggo..',
      '...oobccccboo...',
      '....obccccbo....',
      '...oobbbbbboo...',
      '..fobbo..obbof..',
      '.frokko..okkorf.',
      'frr.ooo..ooo.rrf',
    ],
  },
  voltcub: {
    name: 'Voltcub',
    pal: { o: '#0e1628', b: '#4a6fa5', h: '#8fb3e6', c: '#dfe9f7', e: '#fff36b', k: '#0a0a0a', y: '#ffe14d' },
    rows: [
      '................',
      '................',
      '........o...o...',
      '.......oyo.oho..',
      '.......obbobbbo.',
      '......obhbbbbbbo',
      '......obbebbbbbo',
      '......obbbbbbkko',
      '.y.....obbbcco..',
      '.yy..oobbbcco...',
      '..yoobbbbbbbo...',
      '...obbbcbbbbo...',
      '...obbbbbbbbo...',
      '...obo.obo.obo..',
      '...oo..oo..oo...',
      '................',
    ],
  },
  stormfang: {
    name: 'Stormfang',
    pal: { o: '#0b1222', b: '#3f5f94', h: '#86a9de', c: '#d7e3f5', e: '#fff36b', k: '#0a0a0a', m: '#2a0d0d', y: '#ffe14d' },
    rows: [
      '..........o..o..',
      '.........oyooyo.',
      '........obbbbbbo',
      '...y...obhbbebbo',
      '..yy..oobbbbbbkk',
      '.yyy.oybbbbbmmo.',
      '..yyoyybbbbooo..',
      '...oyybbbcco....',
      '..oybbbbbccco...',
      '.oybbbbbbccbo...',
      'yobbbbbbbbbbo...',
      'yyobbhbbbbbbo...',
      '.yobbbbbbbbbbo..',
      '..obbo.obbo.obo.',
      '..okko.okko.oko.',
      '..oooo.oooo.ooo.',
    ],
  },
  fenrir: {
    name: 'Fenrir Thunderlord',
    pal: { o: '#080e1c', b: '#34507f', h: '#7c9fd6', c: '#cfdcf2', e: '#fff36b', k: '#0a0a0a', m: '#2a0d0d', y: '#ffe14d' },
    rows: [
      '.y.o........o.y.',
      'yy.oo......oo.yy',
      '.yyobo....oboyy.',
      '..yobbo..obboy..',
      '..yobbboobbboy..',
      '.yobhbbbbbbhboy.',
      'yobeebbbbbbeeboy',
      'yobbbbbbbbbbbboy',
      '.yobbbbkkbbbboy.',
      '..yobbmmmmbboy..',
      '..yobkcccckboy..',
      '.yoobccccccbooy.',
      'yobbbccccccbbboy',
      'yobbbbbbbbbbbboy',
      '.obbo.obbo.obbo.',
      '.okko.okko.okko.',
    ],
  },
  glitchling: {
    name: 'Glitchling',
    pal: { o: '#0d0716', b: '#3b1d5e', h: '#7b4fb5', c: '#a77bff', e: '#ff3df2', w: '#ffffff', g: '#3df2ff' },
    rows: [
      '................',
      '................',
      '................',
      '......oooo......',
      '....oobbbboo....',
      '...obhbbbbbbo...',
      '..obhbbwwbbbbo..',
      '..obbbweewbbbo..',
      '.obbbbweewbbbbo.',
      '.obbbbbwwbbbbbo.',
      '.obgbbbbbbbbgbo.',
      '.obbbbcbbcbbbbo.',
      '..obbbbbbbbbbo..',
      '..obbobbobbobo..',
      '...o..o..o..o...',
      '................',
    ],
  },
  nullwraith: {
    name: 'Nullwraith',
    pal: { o: '#0a0512', b: '#341a55', h: '#6e45a8', c: '#a77bff', d: '#040208', e: '#ff3df2', g: '#3df2ff' },
    rows: [
      '......oooo......',
      '....oobbbboo....',
      '...obbbbbbbbo...',
      '..obbddddddbbo..',
      '..obddeddeddbo..',
      '..obddddddddbo..',
      '..obbdggggdbbo..',
      '.obbbbddddbbbbo.',
      'obhbbbbbbbbbbbbo',
      'obbbcbbbbbbcbbbo',
      '.obbbbbbbbbbbbo.',
      '.obbbcbbbbcbbbo.',
      '..obbbbbbbbbbo..',
      '..obobbobbobbo..',
      '..o.o..o..o..o..',
      '................',
    ],
  },
  sovereign: {
    name: 'Void Sovereign',
    pal: { o: '#07030d', b: '#2c1548', h: '#6a40a6', c: '#c4a1ff', d: '#030106', e: '#ff3df2', g: '#3df2ff' },
    rows: [
      '....c.c..c.c....',
      '...cccccccccc...',
      '...obbbbbbbbo...',
      '..obdddeedddbo..',
      '.obdeddddddedbo.',
      '.obdddggggdddbo.',
      'obbbddddddddbbbo',
      'obhbbbbbbbbbbhbo',
      'obbcbbbbbbbbcbbo',
      'gobbbbcbbcbbbbog',
      '.obbbbbbbbbbbbo.',
      'g.obcbbbbbbcbo.g',
      '..obbbbbbbbbbo..',
      '..obobboobbobo..',
      '..o.o..oo..o.o..',
      '................',
    ],
  },
  demonking: {
    name: 'The Demon King',
    pal: { o: '#05030a', k: '#2a2145', b: '#1a1530', h: '#3d3466', c: '#0d0a1a', C: '#3a1670', e: '#c8f4ff', s: '#120e1e', p: '#a66bff' },
    rows: [
      '...p........p...',
      '...ko.oooo.ok...',
      '....kobbbbok....',
      '.....obhbbo.....',
      '.....oebbeo.....',
      '.....obbbbo.....',
      '..ooCobboCoo....',
      '.oCCobhbboCCo...',
      'oCcobbbbbbocCok.',
      'oCcobbbbbbocC.sp',
      'oCcoobbbboocC.sp',
      '.oCcobbbbocCo.sp',
      '.oCcob..bocCo.sp',
      '..oCob..boCo..sp',
      '..oCoh..hoCo...p',
      '...oo....oo.....',
    ],
  },
};

const MONSTER_ART = {
  ouroboros: [
    '................',
    '................',
    '.....oooooo.....',
    '...oobbbbbboo...',
    '..obhbooooobbo..',
    '.obbo.....oobbo.',
    '.obo.......obo..',
    'obbo......oobbo.',
    'obo......obebbo.',
    'obbo.....obbmmo.',
    '.obo.....obbo...',
    '.obbo...oobbo...',
    '..obboooobbo....',
    '...oobbbbo......',
    '.....oooo.......',
    '................',
  ],
  cronbat: [
    '................',
    '................',
    '................',
    'o..............o',
    'o.....o..o.....o',
    'oo...oboobo...oo',
    'obo..obbbbo..obo',
    'obbooebbbbeoobbo',
    'obbbobbbbbbobbbo',
    'o.bbobmkkmbobb.o',
    'o..bobbbbbbob..o',
    '....obbccbbo....',
    '.....obbbbo.....',
    '......oooo......',
    '................',
    '................',
  ],
  skeleton: [
    '................',
    '.....oooooo.....',
    '....obbbbgbo....',
    '...obbbbbbgbo...',
    '...obddbbddbo...',
    '...obdebbedbo...',
    '...obbbddbbbo...',
    '....obmbmbmbo...',
    '.....oooooo.....',
    '...o..obbo..o...',
    '...ob.obbo.bo...',
    '....bobmmbob....',
    '......obbo......',
    '.....ob..bo.....',
    '....obo..obo....',
    '....oo....oo....',
  ],
  turtle: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '....oooooo......',
    '..oobhbbbboo....',
    '.obhbcbbcbbbo.oo',
    'obbcbbbbbbcboqeo',
    'obbbbcbbcbbboqmo',
    'ooooooooooooooo.',
    '.oqqo.....oqqo..',
    '.ooo......ooo...',
    '................',
    '................',
    '................',
  ],
  mimic: [
    '................',
    '................',
    '..oooooooooooo..',
    '.obbbbbbbbbbbbo.',
    '.obeebbbbbbeebo.',
    '.oooooooooooooo.',
    '.owdwdwdwdwdwdo.',
    '.oddddttddddddo.',
    '.odwdwdtwdwdwdo.',
    '.oooooooooooooo.',
    '.obbbbbllbbbbbo.',
    '.obhbbbbbbbbhbo.',
    '.obbbbbbbbbbbbo.',
    '.oooooooooooooo.',
    '................',
    '................',
  ],
  hydra: [
    '.oo....oo....oo.',
    'obeo..obeo..obeo',
    'obbmo.obbmo.obbm',
    '.obo..obo...obo.',
    '..obo.obo..obo..',
    '...obobo.obo....',
    '....obbbobbo....',
    '...obbbbbbbbo...',
    '..obhbbbbbbbbo..',
    '..obbcbbbbcbbo..',
    '.obbbbbbbbbbbbo.',
    '.obbcbbbbbbcbbo.',
    '..obbbbbbbbbbo..',
    '..obbo....obbo..',
    '..okko....okko..',
    '..oooo....oooo..',
  ],
  kraken: [
    '.....oooooo.....',
    '...oobbbbbboo...',
    '..obhbbbbbbbbo..',
    '.obhbbbbbbbbbbo.',
    '.obbwwbbbbwwbbo.',
    '.obbwebbbbewbbo.',
    '.obbbbbccbbbbbo.',
    '..obbbcbbcbbbo..',
    '..obbbbccbbbbo..',
    '.obobobbbbobobo.',
    'obo.obo..obo.obo',
    'ob..ob....bo..bo',
    'o..ob......bo..o',
    '..ob........bo..',
    '.ob..........bo.',
    'o..............o',
  ],
};

const MONSTER_PALS = {
  ouroboros: { o: '#062a26', b: '#26a69a', h: '#80cbc4', e: '#ffeb3b', m: '#b71c1c' },
  cronbat: { o: '#12061f', b: '#4a2a75', h: '#7e57c2', e: '#ff1744', m: '#1a0505', k: '#ffffff', c: '#ffd54f' },
  skeleton: { o: '#1c1a14', b: '#e8e2d0', d: '#141414', e: '#ff1744', m: '#8a8270', g: '#3df2ff' },
  turtle: { o: '#101c14', b: '#546e7a', h: '#90a4ae', c: '#ffca28', q: '#8bc34a', e: '#111111', m: '#33691e' },
  mimic: { o: '#1e0e04', b: '#8d5524', h: '#c68642', l: '#ffd54f', w: '#fff8e1', d: '#2a0a0a', t: '#e91e63', e: '#ffeb3b' },
  hydra: { o: '#1f0606', b: '#cb3837', h: '#ef6b6a', c: '#c9a26b', e: '#ffeb3b', m: '#3a0a0a', k: '#3a0a0a' },
  kraken: { o: '#0a1433', b: '#326ce5', h: '#7aa2ff', w: '#ffffff', e: '#111111', c: '#ffffff' },
};

module.exports = { FORMS, MONSTER_ART, MONSTER_PALS };
